# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SwingJwtHelper < Formula
  desc "JWT helper for swing"
  homepage "https://github.com/nelsonnyan2001/jwt-helper"
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/nelsonnyan2001/jwt-helper/releases/download/v0.0.5/jwt-helper_Darwin_x86_64.tar.gz"
      sha256 "d76f25015efac741b0ed8f2d818d58c8cd960700d015300ecb5fa45fc7e80b1c"

      def install
        bin.install "jwt-helper"
      end
    end
    on_arm do
      url "https://github.com/nelsonnyan2001/jwt-helper/releases/download/v0.0.5/jwt-helper_Darwin_arm64.tar.gz"
      sha256 "98fc0cf4c4c015c8cf410361fad1f0f5eaba23dae11328ea3d8c9199c16579d2"

      def install
        bin.install "jwt-helper"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nelsonnyan2001/jwt-helper/releases/download/v0.0.5/jwt-helper_Linux_x86_64.tar.gz"
        sha256 "dbd58008f00c9729b1775fbe34609075ec0ce1aaff58ad028d747fce5af28dd6"

        def install
          bin.install "jwt-helper"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nelsonnyan2001/jwt-helper/releases/download/v0.0.5/jwt-helper_Linux_arm64.tar.gz"
        sha256 "aed4e9816cd944363bf6f9c66d647658465fc50fe114b8307c233bb4d02d1b29"

        def install
          bin.install "jwt-helper"
        end
      end
    end
  end
end
