# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SwingJwtHelper < Formula
  desc "JWT helper for swing"
  homepage "https://github.com/nelsonnyan2001/jwt-helper"
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/nelsonnyan2001/jwt-helper/releases/download/v0.0.4/jwt-helper_Darwin_x86_64.tar.gz"
      sha256 "e3b488093f9251e8e78e376c6ac9ece30186aac41fd8afb4e31c8852d0a8cc1e"

      def install
        bin.install "jwt-helper"
      end
    end
    on_arm do
      url "https://github.com/nelsonnyan2001/jwt-helper/releases/download/v0.0.4/jwt-helper_Darwin_arm64.tar.gz"
      sha256 "a5266d0ebff79ebeedd2a0fe62d64d6129e04a5b77445223d2ebf701d7f7de7f"

      def install
        bin.install "jwt-helper"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nelsonnyan2001/jwt-helper/releases/download/v0.0.4/jwt-helper_Linux_x86_64.tar.gz"
        sha256 "bcca167f6ce98a89b5c3d669e1d5ff9281feee6658e3cd158e2e82dd3b3a059b"

        def install
          bin.install "jwt-helper"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nelsonnyan2001/jwt-helper/releases/download/v0.0.4/jwt-helper_Linux_arm64.tar.gz"
        sha256 "c3d64c6ca2b25690860777f4782a9922c12c1f24d4b0dbb61665fd9c2aa5ee04"

        def install
          bin.install "jwt-helper"
        end
      end
    end
  end
end
